- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    0xshen: "{{ lookup('env', 'HOME') }}/Documents/0xshen"
  pre_tasks:
    - name: Update Apt
      become: true
      shell: mkdir -p {{ lookup('env','HOME')}}/Documents/0xshen
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/git-setup.yml
    - include: tasks/core-setup.yml
    - include: tasks/nvim.yml
    - include: tasks/brave.yml
    - include: tasks/dotfiles.yml
